### ISSUE TITLE
Changing template files from .html to '.html.twig' to get syntax highlighting 

### ISSUE THREAD

**Issue by antond1990** [getherbie/start-website#7]
IDEs like PHP can handle .twig files better and provide syntax highlighting for Twig. This would make the work a bit easier.

**Comment by tbreuss** [comment]
Hi Anton, thanks for your comment. This makes absolutely sense. I'll try to fix this the next days.

**Comment by tbreuss** [comment]
A have a question about your suggestion.

In Drupal they use:
- home.html.twig
- default.html.twig
- main.css.twig
- etc.

In Twig documentation itself the recommend:
- default.html
- main.html

What is the common standard for naming twig templates? Do you have any suggestions on that?

**Comment by antondachauer** [comment]
Hmm I'm not sure, what the standard/default is. But I know that the standard of Symfony is `home.html.twig` or `export.xml.twig`. And, because IDEs like Phpstorm only show twig syntax highlighting for `.twig` files not for `.html`, I think that's more common. `.twig` maybe also better, because file extensions exists to identify the file type easier. ;-)

**Comment by tbreuss** [comment]
This behavior will be changed in the upcoming 2.0.0 version of Herbie and will then also be available here, see 769bb88ea7712351a4133fa680ff0b9e8ce2b45c.
